### ISSUE TITLE
"Error: wrong value for op: please report as issue"

### ISSUE THREAD

**Issue by sjclements9** [jmsigner/amt#103]
I received the error message "Error: wrong value for op: please report as issue" using the step_lengths function on a track object,  hopefully this is the right place to report -

This is the command and error message.
![image](https://github.com/jmsigner/amt/assets/112018196/12cd1d91-a531-44b3-bc0d-1c4833a4dfeb)

And this is the session info.
![image](https://github.com/jmsigner/amt/assets/112018196/045a159d-13e8-423b-831a-e9d898b08093)

Thank you for your help!

**Comment by jmsigner** [comment]
I think this should be solved with this issued: https://github.com/jmsigner/amt/issues/107. The latest version from GitHub should solve it.
