### ISSUE TITLE
`make_trast()` doesn't accept custom resolution values

### ISSUE THREAD

**Issue by joshcullen** [jmsigner/amt#105]
While using the `make_trast()` function in {amt} v0.2.1.0, the `res` argument doesn't actually let me define a custom value for the resolution of the template raster, but rather uses the default setting in each instance. Upon looking at the code for the function, it looks like this expression `max(c(extent_max(x)/100, 1e-09))` is hard-coded and therefore doesn't allow for any custom values to be used. 

Would you be able to adjust this function to accept custom values for the resolution?

**Comment by jmsigner** [comment]
Thanks for catching this. It's updated on GitHub and will send it to CRAN shortly.
