### ISSUE TITLE
time_of_day_base: maptools vs suncalc

### ISSUE THREAD

**Issue by florianorgeret** [jmsigner/amt#106]
`time_of_day_base` ask for the `maptools` r package to be installed first, but 1) it is not on CRAN anymore (since 2023-07-18) and 2) it looks that it is actually the `suncalc` package that is needed instead

**Comment by jmsigner** [comment]
Which version of `amt`do you use? In the current development version, it should be solved: https://github.com/jmsigner/amt/blob/a1308d55460c998d199b0e192de2a4c816920720/R/time_of_day.R#L56

**Comment by florianorgeret** [comment]
many thanks, I confirm that it is solved in the current development version!
