### ISSUE TITLE
lonlat = TRUE new error

### ISSUE THREAD

**Issue by RonEfrat** [jmsigner/amt#108]
After seeing the solution to [this ](https://github.com/jmsigner/amt/issues/107#issue-2209571526) issue, I installed the new release of amt, and now I get a new error when using lonlat = TRUE in steps or steps_by_burst.

Error in `tibble()`:
! Tibble columns must have compatible sizes.
• Size 905: Existing data.
• Size 820836: Column `sl_`.
ℹ Only values of size one are recycled.

I tried different parts of my data and got the same error, only the numbers following "Size" in the error are different.

**Comment by jmsigner** [comment]
Thanks for reporting. This should be fixed with [a1ae168](https://github.com/jmsigner/amt/commit/a1ae1689738b78fc4ce035ee01c4b1b487eaae6d) and is available in the dev version.
