### ISSUE TITLE
New version-specific error when creating random steps 

### ISSUE THREAD

**Issue by pntoiv** [jmsigner/amt#113]
Hey,

when I create random steps for my step data with the function random_steps(), it runs perfectly in regards to some individuals but others keep getting this error message: 

error: Error in rle(unlist(sapply(bursts, "[[", "burst_"))) : 'x' must be a vector of an atomic type.

I tried to find common factor for all the individuals it did not work on, but it seems to be random. It seems not to be n of the bursts. At first I thought it was that the first burst was numbered above 2 but this was not the case either. 

When I run the exactly same code and data on my home computer, the code works perfectly without any errors. My home computer has R version 4.2.0 and AMT version 0.2.1.0.

My work computer (on which I keep getting the error) has AMT version 0.2.2.0 and R version 4.4.1

**Comment by jmsigner** [comment]
Hi, this was solved with #109, could try with the dev version of the `amt` package?

**Comment by pntoiv** [comment]
> Hi, this was solved with #109, could try with the dev version of the `amt` package?

I have to open this issue again. Yesterday my code worked fine but today I started to getting this same issue (without changing the code at all).

My AMT version is 0.3.0.0. I haven't updated by package from yesterday.
