### ISSUE TITLE
This error emerged again suddenly

### ISSUE THREAD

**Issue by pntoiv** [jmsigner/amt#115]
> Hi, this was solved with #109, could try with the dev version of the `amt` package?

I have to open this issue again. Yesterday my code worked fine but today I started to getting this same issue (without changing the code at all).

My AMT version is 0.3.0.0. I haven't updated by package from yesterday.

_Originally posted by @pntoiv in https://github.com/jmsigner/amt/issues/113#issuecomment-2230547042_

**Comment by jmsigner** [comment]
Is this still relevant?
