### ISSUE TITLE
amt functions not working on personal data while following vignette

### ISSUE THREAD

**Issue by elleryvincent** [jmsigner/amt#116]
I am working through the vignette on personal data, and simultaneously looking at provided fisher data. There are no structural differences between either track, yet I am unable to get past the nesting stage on my own data. I keep getting the error :

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'y' in selecting a method for function 'atan2': argument "y" is missing, with no default

`trk2<-trk1 %>% nest(-id) %>% 
  trk3 = nesttrk %>% mutate(dir_abs = purrr:::map(data, direction_abs,full_circle=TRUE, zero="N"), 
         dir_rel = purrr:::map(data, direction_rel), 
         sl = purrr:::map(data, step_lengths),
         nsd_=purrr:::map(data, nsd))`

and I dont know why, because it appears both sets of data are structured the exact same. Subsetting the data does not help the issue either. Any help would be appreciated. Thank you.

**Comment by bsmity13** [comment]
At first glance, it seems like there's a syntax error in the code snippet you shared. After nesting, you have `trk3 = nesttrk`, which is not a function, so I'm not sure what `%>%` is going to do in that case. Assuming that it is passing something along, it is likely not what the function `direction_abs()` is expecting (or any of the others). 

Start there and let us know if you're still stuck. If you are, a minimal reproducible example is very helpful for troubleshooting (e.g., https://gist.github.com/hadley/270442).
