### ISSUE TITLE
Error: `.data` is a corrupt grouped_df, the `"groups"` attribute must be a data frame

### ISSUE THREAD

**Issue by Sadie-SE** [jmsigner/amt#14]
Could you please help with the following error associated with home range area estimations for nested tracks? (https://movebankworkshopraleighnc.netlify.app/2019outputfiles/testvignettemovebank)

kde.week <- trk %>% 
  mutate(year = year(t_), month = month(t_), week = week(t_)) %>% 
  group_by(id, year, month, week) %>% nest(data=-"id") %>% 
  mutate(kdearea = map(data, ~ hr_kde(., levels=c(0.95)) %>% hr_area)) %>%
  select(id, year, month, week,  kdearea) %>% unnest()

Error: `.data` is a corrupt grouped_df, the `"groups"` attribute must be a data frame

**Comment by jmsigner** [comment]
This due to a change in `purrr` package, try: 

```
kde.week <- trk %>%
mutate(year = year(t_), month = month(t_), week = week(t_)) %>%
nest(data = -c(id, year, month, week)) %>% 
mutate(kdearea = map(data, ~ hr_kde(., levels=c(0.95)) %>% hr_area)) %>%
select(id, year, month, week, kdearea) %>% unnest(cols = kdearea)
```

**Comment by Sadie-SE** [comment]
Great, I appreciate that!
