### ISSUE TITLE
Error in executing code from vignette

### ISSUE THREAD

**Issue by vestlink** [jmsigner/amt#2]
This following creates an error while trying to run the code from the "Fitting a Step-Selection Function" vignette (amt version 0.0.4.0)

> m0 <- ssf1 %>% fit_clogit(case_ ~ forest + strata(step_id_))
Error in eval(predvars, data, env) : object 'case_' not found

**Comment by jmsigner** [comment]
Thanks, could you please post the output of `devtools::session_info()`. Thanks.

**Comment by vestlink** [comment]
disregard the error. I could not reproduce it
