### ISSUE TITLE
Simple shapefile conversion

### ISSUE THREAD

**Issue by coverton-usgs** [jmsigner/amt#22]
I apologize for what I am sure is a simple question but is there a convenient workflow for converting a track to shapefile with metadata intact?  I can convert to other formats and eventually get to a writeOGR but I also run into a lot of errors that way: 

```
example_sp<-as_ltraj(example, infolocs=example)
example_sp<-ltraj2spdf(example_sp)
```
gives ```Error in `[.data.frame`(tr, !is.na(tr$x), c("x", "y")) : 
  undefined columns selected```

but
```
example_move<-as_move(example)
example_sp<-move2ade(example_move)
example_sp@data<-example
```
works for making a spdf

**Comment by jmsigner** [comment]
Sorry, for the delay. I did not get notified for some reason. I am not sure I am sure what you want to do. Do you want to convert a track to a Shapefile with lines?

**Comment by coverton-usgs** [comment]
No worries at all I appreciate that you're willing to devote time to it at all, I know how things go!

Yes, a conversion from track to shapefile (either as points or lines, they both have their use)

**Comment by jmsigner** [comment]
I added to function to the development version of the package. You can source them for time being: 

```
library(amt)
source("https://raw.githubusercontent.com/jmsigner/amt/master/R/coercion.R")

data(deer)

deer %>% as_sf_points() %>% sf::st_write("~/tmp/pts.shp")
deer %>% as_sf_lines() %>% sf::st_write("~/tmp/lines.shp")
```

Does this do what you are after?

**Comment by coverton-usgs** [comment]
The `as_sf_points` is working with an warning message:
```
Warning message:
In CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  :
  GDAL Message 6: Field t_ create as date field, though DateTime requested.
```
But the `as_sf_lines` is giving the error:
```
 Error in MtrxSet(x, dim, type = "MULTILINESTRING", needClosed = FALSE) : 
  is.list(x) is not TRUE 
```

Both rdgal and sf were older version on my machine but updating them had no effect on either the warning or error.  Traceback below:

```
15.
stop(simpleError(msg, call = if (p <- sys.parent(1L)) sys.call(p))) 
14.
stopifnot(is.list(x)) 
13.
MtrxSet(x, dim, type = "MULTILINESTRING", needClosed = FALSE) 
12.
sf::st_multilinestring(l) at coercion.R#111
11.
sf::st_sfc(sf::st_multilinestring(l)) at coercion.R#111
10.
sf::st_sf(sf::st_sfc(sf::st_multilinestring(l))) at coercion.R#111
9.
as_sf_lines.track_xy(.) at coercion.R#88
8.
as_sf_lines(.) 
7.
function_list[[i]](value) 
6.
freduce(value, `_function_list`) 
5.
`_fseq`(`_lhs`) 
4.
eval(quote(`_fseq`(`_lhs`)), env, env) 
3.
eval(quote(`_fseq`(`_lhs`)), env, env) 
2.
withVisible(eval(quote(`_fseq`(`_lhs`)), env, env)) 
1.
z %>% as_sf_lines() %>% sf::st_write("D:/zlines.shp") 

```

**Comment by jmsigner** [comment]
Did you get the same error with the example data set? Could you email me or post the output of `str(z)`?

**Comment by coverton-usgs** [comment]
Yes, that would seem to be the problem.  The example set works fine.  My data has a character column for "id" instead of a numeric "burst" column.

```> str(z)
Classes ‘track_xyt’, ‘track_xy’, ‘tbl_df’, ‘tbl’ and 'data.frame':	777109 obs. of  4 variables:
 $ x_: num  -122 -122 -122 -122 -122 ...
 $ y_: num  38.1 38.1 38.1 38.1 38.1 ...
 $ t_: POSIXct, format: "2015-01-20 17:06:47" "2015-01-20 17:08:22" "2015-01-20 17:10:09" "2015-01-20 17:11:56" ...
 $ id: chr  "X48511914641.WATE.01.1" "X48511914641.WATE.01.1" "X48511914641.WATE.01.1" "X48511914641.WATE.01.1" ...
 - attr(*, "crs_")=Formal class 'CRS' [package "sp"] with 1 slot
  .. ..@ projargs: chr "+proj=longlat +ellps=WGS84 +datum=WGS84 +towgs84=0,0,0"
```

**Comment by coverton-usgs** [comment]
However, converting the id to a numeric still gives me the same error:

```
z2<- z[,c("x_","y_","t_")]
z2$burst<- as.numeric(factor(z$id))
z2 %>% as_sf_lines() %>% sf::st_write("D:/z2lines.shp")
```
Neither changing projection nor limiting to a single individual resolves the issue either

**Comment by jmsigner** [comment]
This should be fixed now. Thanks for reporting back.

**Comment by coverton-usgs** [comment]
Thank you very much for the help, it does work now.  The line file doesn't contain attributes, point file does, and I am having difficulty adding them using merge (its duplicating each record for every burst or id, but I think I am getting closer.  Many thanks!

**Comment by coverton-usgs** [comment]
Hello Johannes,

I just wanted to let you know that I received provisional approvals for release.  I am hoping that they have made this repo public by now, If I make any changes to the code it will be reflected here:

https://code.usgs.gov/wildlife-telemetry-toolkit/telemetry-code-and-collaborations

Many thanks for your help,
C
