### ISSUE TITLE
update_vonmises function

### ISSUE THREAD

**Issue by CBeardsworth** [jmsigner/amt#29]
If the cos_ta_ coefficient is negative then this row: 
new_conc <- unname(dist$params$kappa + beta_cos_ta)
can lead to a negative kappa value, which is (apparently) not allowed. Should this be abs(unname(dist$params$kappa + beta_cos_ta))?

**Comment by jmsigner** [comment]
Thanks for bringing this up, this not entirely resolved yet. We will give an error/warning in the next update.
