### ISSUE TITLE
indicate column from input data.frame to mk_track using tidyselect

### ISSUE THREAD

**Issue by bniebuhr** [jmsigner/amt#33]
Hi!

I have being using `amt` and to start each process we need to use the function `mk_track`.
To use it, we pass as argument the coordinates and time (x, y, t), and each of the other columns must be names.
For instance:

```r
mk_track(my_data_frame, .x = x, .y = y, .t = timestamp, collar_id, animal_id, burst, year, 
    health_condition, sex, body_mass, crs = 4326)
```

It is nice that there is the option `all_cols` that can be set to `TRUE`, so it does not get tiring to include all columns all the time.

I was thinking, however, if it would not make sense to include some kind of tidyselect structure to be able to include columns by number of names in a sequence, to make this process easier. Such as `mk_track(my_data_frame, x, y, timestamp, cols = collar_id:body_mass)` or `mk_track(my_data_frame, x, y, timestamp, cols = 4:10)`.

Or maybe it is better to keep the function simple and recommend the use of `dplyr::select` before using `mk_track`?

Something like
```r
my_data_frame %>%
    dplyr::select(collar_id:body_mass) %>%
    mk_track(x, y, timestamp, all_cols = TRUE, crs = 4326)
```

**Comment by jmsigner** [comment]
@bniebuhr  thanks for your suggestion. I think this would be a sensible thing to do. But I am lacking time to do this at the moment. If you wanna give it a try, I am happy to accept pull requests ;).

**Comment by bniebuhr** [comment]
Ok! I am not well versed on R packages yet but I'll give it a try! =)

**Comment by jmsigner** [comment]
I can't remember with which version, but this should be all implemented now.
