### ISSUE TITLE
error with hr_od and as_telemetry

### ISSUE THREAD

**Issue by bjpadilla** [jmsigner/amt#34]
Hi, Ive been having an error pop up that is stopping an analysis that previously ran without error with the same script and dataset. I've been digging into the error and I think the real issue is pooping up with the `as_telemetry` function while prepping the data for the `fit_ctmm` within the `hr_od`. 
The odd thing is that it appears to only show up for some of the datasets. See the example below. I've included a track dataset with multiple animals that is then nested by `id`, `year`, and `season`. The `as_telemetry` function works for the first row of the data, but not for the second row, which is where the `hr_od` analysis gets stopped. 

[trk_data.Rdata.zip](https://github.com/jmsigner/amt/files/5754664/trk_data.Rdata.zip)
```
## Load required packages
library(amt)
library(ctmm)
library(raster)
library(tidyverse)

load("trk_data.Rdata")
# nest the data by year, id and season
elks <- trk %>% nest(data = -c(id, year,season)) %>% 
  mutate(n = map_int(data, nrow)) %>% 
  filter(n > 20)
elks1 <- elks %>%
  mutate(
    "hr_od_ou" = map(data, ~ hr_od(., model = fit_ctmm(., "ou"))),
    "hr_od_50" = map(data, ~ hr_od(., model = fit_ctmm(., "ou"), levels = c(0.5)))
  )

# issue appears to be with `as_telemetry` but not with all of the rows in nested data
## this works
as_telemetry(elks$data[[1]]) 
## but this doesnt 
as_telemetry(elks$data[[2]])
```

**Comment by jmsigner** [comment]
I suspect you assigned the data the wrong projection. It appears that the data is in `epsg:4326` but has the projection string of a NAD projection

```
amt::get_crs(elks$data[[2]])
CRS arguments:
 +proj=utm +zone=18 +datum=NAD83 +units=m +no_defs 
```

Using a geographic projection seems to work:

```
elks$data[[2]] %>% make_track(x_, y_, t_, crs = CRS("+init=epsg:4326")) %>% 
  as_telemetry()
```

**Comment by bjpadilla** [comment]
Ahh, seems I must have altered the code from before regarding projections and not realized it. Thanks!
