### ISSUE TITLE
3D data processing?

### ISSUE THREAD

**Issue by khufkens** [jmsigner/amt#38]
Hi, first of all thanks for providing the package! It has made past analysis really easy.

In an analysis I dealt with recently I did run into some limitations, mostly that the package is currently dealing with 2D data. This seems the norm in the field (I rolled into a movement ecology project by accident, so forgive my ignorance if my take on this is wrong). I was wondering if there are planned provisions for including an option of managing 3D data (height / depth).

This would basically be an extension of Potential Path Volumes for birds (https://movementecologyjournal.biomedcentral.com/articles/10.1186/s40462-019-0158-4) or fish (https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.13232) or similar concepts I guess.

Although some analysis can be reduced to 2D framework, some can't (or I haven't found an explicit solution for it anyway). I was wondering if there are provisions to add height / depth to the modelling environment (or if there are constraints that make this not feasible). Again, I might be missing large sections of literature but the things I do find seem rather recent.

**Comment by jmsigner** [comment]
Thanks for your suggestion. I agree that much of the analyses implemented, however some packages (e.g., [CTMM](https://rdrr.io/cran/ctmm/man/akde.html)) support 3D data. At the moment I have unfortunately no capacity to work on this in the new future. In case you want to give it a try let me know.

**Comment by khufkens** [comment]
Thanks for the pointers. I understand the time limitations. Should I pick this up as a side project I'll get back in touch!
