### ISSUE TITLE
Make obvious message optional

### ISSUE THREAD

**Issue by courtiol** [jmsigner/amt#40]
The function amt::mk_track() is verbose:
https://github.com/jmsigner/amt/blob/6510122aa9bdca7b8be1e2e050698f02754e5148/R/track.R#L66
when called repeatedly within a wrapper it can annoyingly cover the screen.

It is not particularly informative since it just reflects what the user decides to do.

So it would be great if you could add a `verbose = TRUE` argument to the function or find an alternative to make such display optional.

**Comment by jmsigner** [comment]
Good point. The development version with update (541d876) now has this implemented.
