### ISSUE TITLE
optional output crs for bbox

### ISSUE THREAD

**Issue by bniebuhr** [jmsigner/amt#43]
Hi!

I was looking at the bbox function and it is nice it allows one to include a buffer. This might be quite useful!

In one of my functions to do something similar, I have added an additional parameter to allow the reprojection of the bbox. This might be particularly interesting if one has a movement dataset on UTM and wants to get the bbox in lat-lon coordinates (EPSG 4326), for instance, to use in functions such as `ggmap`, which generally use such projection.

The part of code to do this looks like:

```r
 box <- obj %>% 
      sf::st_bbox() %>% 
      matrix(ncol = 2, byrow = T) %>%
      as.data.frame() %>% 
      sf::st_as_sf(coords = c("V1", "V2"), crs = sf::st_crs(obj)) %>% 
      sf::st_transform(crs = crs) %>% 
      sf::st_bbox()
```

where in this case `obj` is an `sf` input object and `crs` is the desired coordinate reference system.
The idea of this block is to avoid reprojecting the whole movement dataset, which might take time depending on its size.

So I was wondering whether it would not be possible to add such an option to `amt::bbox()`. I can try it, make an example, and make a pull request, if you think it is worth it.

**Comment by jmsigner** [comment]
Sorry for the long delay, I am trying to catch up. Nice idea, but dont you think what `st_transofrm is sufficient?

```
library(amt)
library(sf)
data(deer)

bbox(deer, sf = TRUE) %>% 
  st_transform(4326)
```

I think it would be a good idea to make `sf = TRUE` the default. Let me know what you think.

**Comment by bniebuhr** [comment]
Oh, I did not know about the `sf` parameter in bbox. That's is cool and indeed much simpler and elegant! In that case, there is no need to implement anything else within `amt::bbox()`.

Regarding making `sf = TRUE` the default, I am not sure, because it would bring a different behavior compared to the base bbox function.
This by itself is not a problem, if the function is useful in the context of `amt`.
Maybe an alternative would just to add this as an example for the `bbox` function, so that it is more explicit for users that this is possible?

```r
bbox(deer, sf = TRUE) %>% 
  st_transform(4326)
```

**Comment by jmsigner** [comment]
Good point. I added an example (22f0a1c).
