### ISSUE TITLE
missing data from amt arXiv

### ISSUE THREAD

**Issue by CTO22** [jmsigner/amt#5]
Can you push the data relating to the fisher use cases:
dat <- read_csv("data/Martes pennanti LaPoint New York.csv") %>%
-and-
land_use <- raster("data/landuse_study_area.tif")
to the master?  I tried accessing the . rda  and it is not loading and those data are not available with the package.

Thus I can not run the code provided in the supplement to the arXiv (8 May 2018)

**Comment by CTO22** [comment]
Note I was able to get the data via:


loginStored <- movebankLogin(username="MovebankWorkshop", assword="genericuserforthisexercise")
getMovebankStudy(study="Martes pennanti LaPoint New York", login=loginStored) # see study-level nfo
fisher.move <- getMovebankData(study="Martes pennanti LaPoint New York", login=loginStored)

fisher.dat <- as(fisher.move, "data.frame")


dat <- fisher.dat %>%
  filter(!is.na("location_lat")) %>%
  select(x = "location_long", y = "location_lat",
         t = "timestamp", id = "local_identifier") %>%
  filter(id %in% c("F1", "F2", "F3", "M1", "M2", "M3")) # for example 2
## assuming the first 3 males are the ones referenced in the supplement

**Comment by jmsigner** [comment]
The landuse data is included in `amt` now (not properly documented yet). You can load it with: 

```
data("amt_fisher_lu", package = "amt")

```
