### ISSUE TITLE
Warning message on convergence

### ISSUE THREAD

**Issue by anjankatna** [jmsigner/amt#53]
Hello again,

I created an iSSF model, and got the following warning:

##
Warning message:
In fitter(X, Y, istrat, offset, init, control, weights = weights,  :
  Loglik converged before variable  4 ; coefficient may be infinite. 
##

Is this something to be overly concerned about. I do get the model results.

Also, is there an option or a possibility of running model diagnostics (or is it required - asking in case a reviewer asks for it).

Regards,
Anjan

**Comment by jmsigner** [comment]
It is likely that your SE might be very high. But it's hard to diagnose without seeing the data.
