### ISSUE TITLE
Create track from a sf point geometry

### ISSUE THREAD

**Issue by PM-deer** [jmsigner/amt#72]
I have a dataframe of gps locations, but the locations are in one column as a sf point (lat,lon). Is there a way to create an amt track from a sf point geometry or will I need to seperate the column into two different columns to have a lat and lon column?
Thanks

**Comment by jmsigner** [comment]
There is a function `as_track()` which has a method for `sfc_POINT`. Hopefully, this helps, otherwise please let me know.

**Comment by PM-deer** [comment]
That worked. I have one more question, is there a way to use the as_track() function and keep a timestamp in the track? 
Thank you.
