### ISSUE TITLE
Error in r[i1] - r[-length(r):-(length(r) - lag + 1L)] : non-numeric argument to binary operator

### ISSUE THREAD

**Issue by yuxin321** [jmsigner/amt#78]
Hi, I try to run the code of transforming geographical coordinates in a article named "Animal movement tools (amt): R package for managing tracking data and conducting habitat selection analyses".
And then there is an error : Error in r[i1] - r[-length(r):-(length(r) - lag + 1L)] : non-numeric argument to binary operator.

I ran it completely according to the code in the article and the sample data downloaded from the movebank.

I would appreciate it if you can tell me how to solve it.

Thanks for your generous help!

**Comment by jmsigner** [comment]
Hi, could you send me a small subset of the data that produces the error? Feel free to send it by email.
