### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [jmsigner/amt#83]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

If there are no good alternatives for `maptools::crepuscule`,  `maptools::sunriset`, please raise an issue at https://github.com/r-spatial/evolution/issues asking for the functionality you need to be moved to **sp**.

**Comment by jmsigner** [comment]
@rsbivand thanks for reminder. I have made all requested changes to the `amt` package. I am waiting for the newest `terra` version (there was a small bug) and will submit shortly afterwards a new version of `amt` to CRAN.

**Comment by rsbivand** [comment]
Run with sp evolution status 2 and without retiring packages on the library path, I see:
[00check.log](https://github.com/jmsigner/amt/files/11137755/00check.log)
which I think is not protecting against `move` having a strong dependency on `rgdal`. 
Using:
```
move_obj <- try(as_move(deer))
if (!inherits(move_obj, "try-error")) print(move_obj)
```
should resolve that problem, but please do try to reproduce locally, as my `CMD check` stops at first error.

**Comment by rsbivand** [comment]
Please also see https://r-spatial.org/r/2023/04/10/evolution3.html

**Comment by rsbivand** [comment]
Looks OK with `move 4.2.2`, thanks.
