### ISSUE TITLE
can't find sl_shape, sl_scale and function

### ISSUE THREAD

**Issue by bserranito** [jmsigner/amt#91]
I apologize if this question was already asked or inappropriate, but I currently want to reproduce the code described in Signer et al., 2018.

Everything work well but when I try to obtain the parameters estimates using the sl_scale and sl_shape functions, R warns that these functions doesn't exist anymore. Are there any other function leading to the same result ?

I'm using the amt package vers 0.2.1.0

Thanks

**Comment by Daviser95** [comment]
Dear @jmsigner, 
I am also trying to follow the example in your publication, and I would like to the new function of the original 'movement_kernel' function. 

Thank you in advance!
Davide

**Comment by jmsigner** [comment]
Hi Davide, coudl you post a bit more context of what you are trying to do?
