### ISSUE TITLE
how to output shape file of kde results?

### ISSUE THREAD

**Issue by leiallen521** [jmsigner/amt#97]
I have multiple animals need to calculate kde, but i don't know how to use  writeORG function to output shpe file based on results from  hr_kde function.  I find a example in stackoverflow [here](https://stackoverflow.com/questions/59788304/exporting-a-contoured-kernel-density-estimation-plot-to-raster-or-shapefile-form) ,but it doesn't work.  Can you provide a simple code to realize that ? Thx!!!

**Comment by jmsigner** [comment]
What is the error that you encounter, here is a simple example: 

```
library(amt)

data(amt_fisher)

amt_fisher |> nest(data = -id) |> 
  mutate(kde = map(data, ~ .x |> hr_kde())) |> hr_to_sf(kde, id) |> 
  st_write(file.path(tempdir(), "hrs.shp"))
  
```
